name: CI - Build and Test

on:
  push:
    branches: [ main, develop, copilot/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting (if available)
      run: npm run lint --if-present
      continue-on-error: true
      
    - name: Run tests
      run: npm test -- --coverage --maxWorkers=2
      
    - name: Upload test coverage
      uses: codecov/codecov-action@v4
      if: always()
      continue-on-error: true
      with:
        files: ./coverage/coverage-final.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage/
          jest-results.json
        retention-days: 30
    
    - name: Build Expo app
      run: npx expo export:web
      continue-on-error: true
      
    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
          .expo/
        retention-days: 7
