name: CD - Deploy to Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Run tests before deploy
      run: npm test -- --maxWorkers=2
      
    - name: Publish to Expo (staging)
      if: github.event.inputs.environment == 'staging' || github.event.inputs.environment == ''
      run: |
        npx expo publish --release-channel staging --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Publish to Expo (production)
      if: github.event.inputs.environment == 'production'
      run: |
        npx expo publish --release-channel production --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Create deployment summary
      run: |
        echo "## Deployment Summary :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ github.event.inputs.environment || 'staging' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Actor**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Expo App" >> $GITHUB_STEP_SUMMARY
        echo "View at: https://expo.dev/@${{ secrets.EXPO_USERNAME }}/docente-plus" >> $GITHUB_STEP_SUMMARY
    
    - name: Notify deployment status
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const status = '${{ job.status }}';
          const environment = '${{ github.event.inputs.environment || 'staging' }}';
          const emoji = status === 'success' ? '✅' : '❌';
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: `${emoji} Deployment to **${environment}** ${status === 'success' ? 'succeeded' : 'failed'}\n\nWorkflow: ${context.workflow}`
          });
