name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run E2E tests daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  e2e-web:
    name: E2E Tests (Web)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
      
    - name: Build web app
      run: npx expo export:web
      
    - name: Start web server
      run: |
        npx serve dist -l 3000 &
        echo "WEB_SERVER_PID=$!" >> $GITHUB_ENV
        # Wait for server to be ready
        timeout 30 bash -c 'until curl -f http://localhost:3000; do sleep 1; done'
      
    - name: Run E2E tests
      run: |
        if [ -d "__tests__/e2e" ]; then
          npm run test:e2e
        else
          echo "⚠️ E2E tests directory not found, running smoke tests instead"
          node __tests__/e2e-smoke.test.js
        fi
      continue-on-error: true
      
    - name: Upload E2E test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 30
        
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-screenshots
        path: |
          test-results/**/*.png
          playwright-report/**/*.png
        retention-days: 7
    
    - name: Stop web server
      if: always()
      run: |
        if [ ! -z "$WEB_SERVER_PID" ]; then
          kill $WEB_SERVER_PID || true
        fi
        
  e2e-summary:
    name: E2E Summary
    runs-on: ubuntu-latest
    needs: [e2e-web]
    if: always()
    
    steps:
    - name: Create test summary
      run: |
        echo "## E2E Test Results :test_tube:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform**: Web" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ${{ needs.e2e-web.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.e2e-web.result }}" = "success" ]; then
          echo "✅ All E2E tests passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Some E2E tests failed or were skipped" >> $GITHUB_STEP_SUMMARY
        fi
