name: Notifications

on:
  workflow_run:
    workflows: ["CI - Build and Test", "CD - Deploy to Staging", "E2E Tests"]
    types:
      - completed

jobs:
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Determine workflow outcome
      id: outcome
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
          echo "emoji=✅" >> $GITHUB_OUTPUT
          echo "status=succeeded" >> $GITHUB_OUTPUT
          echo "color=28a745" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.workflow_run.conclusion }}" = "failure" ]; then
          echo "emoji=❌" >> $GITHUB_OUTPUT
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "color=d73a49" >> $GITHUB_OUTPUT
        else
          echo "emoji=⚠️" >> $GITHUB_OUTPUT
          echo "status=completed with warnings" >> $GITHUB_OUTPUT
          echo "color=ffa500" >> $GITHUB_OUTPUT
        fi
    
    - name: Create issue comment on failure
      if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          // Get the PR associated with this workflow run
          const pulls = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`
          });
          
          if (pulls.data.length > 0) {
            const pr = pulls.data[0];
            const workflowName = '${{ github.event.workflow_run.name }}';
            const branch = '${{ github.event.workflow_run.head_branch }}';
            const sha = '${{ github.event.workflow_run.head_sha }}';
            const runNumber = '${{ github.event.workflow_run.run_number }}';
            const runUrl = '${{ github.event.workflow_run.html_url }}';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '## ❌ Workflow Failed: ' + workflowName + '\n\n' +
                    '**Branch**: `' + branch + '`\n' +
                    '**Commit**: ' + sha + '\n' +
                    '**Run**: [#' + runNumber + '](' + runUrl + ')\n\n' +
                    'Please check the workflow logs for details.'
            });
          }
    
    - name: Post workflow summary
      uses: actions/github-script@v7
      with:
        script: |
          const workflow = '${{ github.event.workflow_run.name }}';
          const status = '${{ steps.outcome.outputs.status }}';
          const emoji = '${{ steps.outcome.outputs.emoji }}';
          const branch = '${{ github.event.workflow_run.head_branch }}';
          const runUrl = '${{ github.event.workflow_run.html_url }}';
          
          console.log(`${emoji} Workflow "${workflow}" ${status}`);
          console.log(`Branch: ${branch}`);
          console.log(`Run URL: ${runUrl}`);
          
          core.summary
            .addHeading(`${emoji} Workflow Notification`)
            .addTable([
              [{data: 'Field', header: true}, {data: 'Value', header: true}],
              ['Workflow', workflow],
              ['Status', status],
              ['Branch', branch],
              ['Triggered by', '${{ github.event.workflow_run.triggering_actor.login }}'],
              ['Run Number', '#${{ github.event.workflow_run.run_number }}']
            ])
            .addLink('View Workflow Run', runUrl)
            .write();
